# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{faetr}
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bodaniel Jeanes", "Jack Chen"]
  s.date = %q{2009-10-13}
  s.description = %q{Collection of nice Ruby object extensions}
  s.email = %q{me@bjeanes.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "faetr.gemspec",
     "lib/faetr.rb",
     "lib/faetr/array_ext.rb",
     "lib/faetr/class_ext.rb",
     "lib/faetr/range_ext.rb",
     "lib/faetr/symbol_ext.rb",
     "lib/faetr/warn_define.rb",
     "spec/array_ext_spec.rb",
     "spec/range_ext_spec.rb",
     "spec/spec_helper.rb",
     "spec/symbol_ext_spec.rb",
     "spec/warn_define_spec.rb"
  ]
  s.homepage = %q{http://github.com/bjeanes/faetr}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{faetr}
  s.rubygems_version = %q{1.3.4}
  s.summary = %q{Collection of nice Ruby object extensions}
  s.test_files = [
    "spec/array_ext_spec.rb",
     "spec/range_ext_spec.rb",
     "spec/spec_helper.rb",
     "spec/symbol_ext_spec.rb",
     "spec/warn_define_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end
